# -*- coding: utf-8 -*-
"""
/***************************************************************************
 actualizacioncatastralv2
                                 A QGIS plugin
 actualizacioncatastralv2
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-02-27
        copyright            : (C) 2018 by actualizacioncatastralv2
        email                : actualizacioncatastralv2
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load actualizacioncatastralv2 class from file actualizacioncatastralv2.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .actualizacioncatastralv2 import actualizacioncatastralv2
    return actualizacioncatastralv2(iface)
